/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidarRouteImport } from './routes/validar'
import { Route as ReescreverRouteImport } from './routes/reescrever'
import { Route as RadarMercadoRouteImport } from './routes/radar-mercado'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as ProspeccaoRouteImport } from './routes/prospeccao'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as ObjecoesRouteImport } from './routes/objecoes'
import { Route as MarcaRouteImport } from './routes/marca'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitPublicacaoRouteImport } from './routes/kit-publicacao'
import { Route as EstudosDeCasoRouteImport } from './routes/estudos-de-caso'
import { Route as CustosRouteImport } from './routes/custos'
import { Route as CopyRouteImport } from './routes/copy'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConcorrentesRouteImport } from './routes/concorrentes'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'

const ValidarRoute = ValidarRouteImport.update({
  id: '/validar',
  path: '/validar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReescreverRoute = ReescreverRouteImport.update({
  id: '/reescrever',
  path: '/reescrever',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarMercadoRoute = RadarMercadoRouteImport.update({
  id: '/radar-mercado',
  path: '/radar-mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspeccaoRoute = ProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjecoesRoute = ObjecoesRouteImport.update({
  id: '/objecoes',
  path: '/objecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaRoute = MarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitPublicacaoRoute = KitPublicacaoRouteImport.update({
  id: '/kit-publicacao',
  path: '/kit-publicacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudosDeCasoRoute = EstudosDeCasoRouteImport.update({
  id: '/estudos-de-caso',
  path: '/estudos-de-caso',
  getParentRoute: () => rootRouteImport,
} as any)
const CustosRoute = CustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyRoute = CopyRouteImport.update({
  id: '/copy',
  path: '/copy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcorrentesRoute = ConcorrentesRouteImport.update({
  id: '/concorrentes',
  path: '/concorrentes',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/concorrentes': typeof ConcorrentesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/copy': typeof CopyRoute
  '/custos': typeof CustosRoute
  '/estudos-de-caso': typeof EstudosDeCasoRoute
  '/kit-publicacao': typeof KitPublicacaoRoute
  '/login': typeof LoginRoute
  '/marca': typeof MarcaRoute
  '/objecoes': typeof ObjecoesRoute
  '/performance': typeof PerformanceRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/radar': typeof RadarRoute
  '/radar-mercado': typeof RadarMercadoRoute
  '/reescrever': typeof ReescreverRoute
  '/validar': typeof ValidarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/concorrentes': typeof ConcorrentesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/copy': typeof CopyRoute
  '/custos': typeof CustosRoute
  '/estudos-de-caso': typeof EstudosDeCasoRoute
  '/kit-publicacao': typeof KitPublicacaoRoute
  '/login': typeof LoginRoute
  '/marca': typeof MarcaRoute
  '/objecoes': typeof ObjecoesRoute
  '/performance': typeof PerformanceRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/radar': typeof RadarRoute
  '/radar-mercado': typeof RadarMercadoRoute
  '/reescrever': typeof ReescreverRoute
  '/validar': typeof ValidarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/concorrentes': typeof ConcorrentesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/copy': typeof CopyRoute
  '/custos': typeof CustosRoute
  '/estudos-de-caso': typeof EstudosDeCasoRoute
  '/kit-publicacao': typeof KitPublicacaoRoute
  '/login': typeof LoginRoute
  '/marca': typeof MarcaRoute
  '/objecoes': typeof ObjecoesRoute
  '/performance': typeof PerformanceRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/radar': typeof RadarRoute
  '/radar-mercado': typeof RadarMercadoRoute
  '/reescrever': typeof ReescreverRoute
  '/validar': typeof ValidarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/calendario'
    | '/concorrentes'
    | '/configuracoes'
    | '/copy'
    | '/custos'
    | '/estudos-de-caso'
    | '/kit-publicacao'
    | '/login'
    | '/marca'
    | '/objecoes'
    | '/performance'
    | '/prospeccao'
    | '/radar'
    | '/radar-mercado'
    | '/reescrever'
    | '/validar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/calendario'
    | '/concorrentes'
    | '/configuracoes'
    | '/copy'
    | '/custos'
    | '/estudos-de-caso'
    | '/kit-publicacao'
    | '/login'
    | '/marca'
    | '/objecoes'
    | '/performance'
    | '/prospeccao'
    | '/radar'
    | '/radar-mercado'
    | '/reescrever'
    | '/validar'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/calendario'
    | '/concorrentes'
    | '/configuracoes'
    | '/copy'
    | '/custos'
    | '/estudos-de-caso'
    | '/kit-publicacao'
    | '/login'
    | '/marca'
    | '/objecoes'
    | '/performance'
    | '/prospeccao'
    | '/radar'
    | '/radar-mercado'
    | '/reescrever'
    | '/validar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CalendarioRoute: typeof CalendarioRoute
  ConcorrentesRoute: typeof ConcorrentesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CopyRoute: typeof CopyRoute
  CustosRoute: typeof CustosRoute
  EstudosDeCasoRoute: typeof EstudosDeCasoRoute
  KitPublicacaoRoute: typeof KitPublicacaoRoute
  LoginRoute: typeof LoginRoute
  MarcaRoute: typeof MarcaRoute
  ObjecoesRoute: typeof ObjecoesRoute
  PerformanceRoute: typeof PerformanceRoute
  ProspeccaoRoute: typeof ProspeccaoRoute
  RadarRoute: typeof RadarRoute
  RadarMercadoRoute: typeof RadarMercadoRoute
  ReescreverRoute: typeof ReescreverRoute
  ValidarRoute: typeof ValidarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validar': {
      id: '/validar'
      path: '/validar'
      fullPath: '/validar'
      preLoaderRoute: typeof ValidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reescrever': {
      id: '/reescrever'
      path: '/reescrever'
      fullPath: '/reescrever'
      preLoaderRoute: typeof ReescreverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar-mercado': {
      id: '/radar-mercado'
      path: '/radar-mercado'
      fullPath: '/radar-mercado'
      preLoaderRoute: typeof RadarMercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospeccao': {
      id: '/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof ProspeccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objecoes': {
      id: '/objecoes'
      path: '/objecoes'
      fullPath: '/objecoes'
      preLoaderRoute: typeof ObjecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca': {
      id: '/marca'
      path: '/marca'
      fullPath: '/marca'
      preLoaderRoute: typeof MarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit-publicacao': {
      id: '/kit-publicacao'
      path: '/kit-publicacao'
      fullPath: '/kit-publicacao'
      preLoaderRoute: typeof KitPublicacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudos-de-caso': {
      id: '/estudos-de-caso'
      path: '/estudos-de-caso'
      fullPath: '/estudos-de-caso'
      preLoaderRoute: typeof EstudosDeCasoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custos': {
      id: '/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof CustosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy': {
      id: '/copy'
      path: '/copy'
      fullPath: '/copy'
      preLoaderRoute: typeof CopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concorrentes': {
      id: '/concorrentes'
      path: '/concorrentes'
      fullPath: '/concorrentes'
      preLoaderRoute: typeof ConcorrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  CalendarioRoute: CalendarioRoute,
  ConcorrentesRoute: ConcorrentesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CopyRoute: CopyRoute,
  CustosRoute: CustosRoute,
  EstudosDeCasoRoute: EstudosDeCasoRoute,
  KitPublicacaoRoute: KitPublicacaoRoute,
  LoginRoute: LoginRoute,
  MarcaRoute: MarcaRoute,
  ObjecoesRoute: ObjecoesRoute,
  PerformanceRoute: PerformanceRoute,
  ProspeccaoRoute: ProspeccaoRoute,
  RadarRoute: RadarRoute,
  RadarMercadoRoute: RadarMercadoRoute,
  ReescreverRoute: ReescreverRoute,
  ValidarRoute: ValidarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
