/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidarRouteImport } from './routes/validar'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as ObjecoesRouteImport } from './routes/objecoes'
import { Route as MarcaRouteImport } from './routes/marca'
import { Route as CustosRouteImport } from './routes/custos'
import { Route as CopyRouteImport } from './routes/copy'
import { Route as ConcorrentesRouteImport } from './routes/concorrentes'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as IndexRouteImport } from './routes/index'

const ValidarRoute = ValidarRouteImport.update({
  id: '/validar',
  path: '/validar',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjecoesRoute = ObjecoesRouteImport.update({
  id: '/objecoes',
  path: '/objecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaRoute = MarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => rootRouteImport,
} as any)
const CustosRoute = CustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyRoute = CopyRouteImport.update({
  id: '/copy',
  path: '/copy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcorrentesRoute = ConcorrentesRouteImport.update({
  id: '/concorrentes',
  path: '/concorrentes',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/concorrentes': typeof ConcorrentesRoute
  '/copy': typeof CopyRoute
  '/custos': typeof CustosRoute
  '/marca': typeof MarcaRoute
  '/objecoes': typeof ObjecoesRoute
  '/performance': typeof PerformanceRoute
  '/radar': typeof RadarRoute
  '/validar': typeof ValidarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/concorrentes': typeof ConcorrentesRoute
  '/copy': typeof CopyRoute
  '/custos': typeof CustosRoute
  '/marca': typeof MarcaRoute
  '/objecoes': typeof ObjecoesRoute
  '/performance': typeof PerformanceRoute
  '/radar': typeof RadarRoute
  '/validar': typeof ValidarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/concorrentes': typeof ConcorrentesRoute
  '/copy': typeof CopyRoute
  '/custos': typeof CustosRoute
  '/marca': typeof MarcaRoute
  '/objecoes': typeof ObjecoesRoute
  '/performance': typeof PerformanceRoute
  '/radar': typeof RadarRoute
  '/validar': typeof ValidarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/concorrentes'
    | '/copy'
    | '/custos'
    | '/marca'
    | '/objecoes'
    | '/performance'
    | '/radar'
    | '/validar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/concorrentes'
    | '/copy'
    | '/custos'
    | '/marca'
    | '/objecoes'
    | '/performance'
    | '/radar'
    | '/validar'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/concorrentes'
    | '/copy'
    | '/custos'
    | '/marca'
    | '/objecoes'
    | '/performance'
    | '/radar'
    | '/validar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  ConcorrentesRoute: typeof ConcorrentesRoute
  CopyRoute: typeof CopyRoute
  CustosRoute: typeof CustosRoute
  MarcaRoute: typeof MarcaRoute
  ObjecoesRoute: typeof ObjecoesRoute
  PerformanceRoute: typeof PerformanceRoute
  RadarRoute: typeof RadarRoute
  ValidarRoute: typeof ValidarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validar': {
      id: '/validar'
      path: '/validar'
      fullPath: '/validar'
      preLoaderRoute: typeof ValidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objecoes': {
      id: '/objecoes'
      path: '/objecoes'
      fullPath: '/objecoes'
      preLoaderRoute: typeof ObjecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca': {
      id: '/marca'
      path: '/marca'
      fullPath: '/marca'
      preLoaderRoute: typeof MarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custos': {
      id: '/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof CustosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy': {
      id: '/copy'
      path: '/copy'
      fullPath: '/copy'
      preLoaderRoute: typeof CopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concorrentes': {
      id: '/concorrentes'
      path: '/concorrentes'
      fullPath: '/concorrentes'
      preLoaderRoute: typeof ConcorrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  ConcorrentesRoute: ConcorrentesRoute,
  CopyRoute: CopyRoute,
  CustosRoute: CustosRoute,
  MarcaRoute: MarcaRoute,
  ObjecoesRoute: ObjecoesRoute,
  PerformanceRoute: PerformanceRoute,
  RadarRoute: RadarRoute,
  ValidarRoute: ValidarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
